Updated lark.fg and test cases to support basic functionalites
rajp152k/Compilers-II pull request #10
Opened 2020-10-19 17:44 UTC by nisargshah2000

2020-10-19 19:02 UTC, vedantsingh1404 commented on parser/fg.lark
> +function_stmt : dependent_variable "<-" (single_function | function_list)
should be independent variable instead.

2020-10-19 19:10 UTC, vedantsingh1404 requested changes

2020-10-19 19:10 UTC, vedantsingh1404 commented on parser/fg.lark
> +ID : (LCASE_LETTER)+
Why can't the figure name consist of upper case letters?

2020-10-19 19:10 UTC, vedantsingh1404 commented on parser/fg.lark
> +range_stmt : variable "<-" (points | range)
why not use independent variable instead?

2020-10-19 19:10 UTC, vedantsingh1404 commented on parser/fg.lark
> +indendent_variable : ID
typo x 2

2020-10-19 19:13 UTC, nisargshah2000 commented on parser/fg.lark
> +ID : (LCASE_LETTER)+
Just for simplicity, all variable and ID are lower case.

2020-10-19 19:14 UTC, nisargshah2000 commented on parser/fg.lark
> +range_stmt : variable "<-" (points | range)
We can use that also, but it is not used just for readability. In general, dependent and independent variable comes together.

2020-10-19 19:15 UTC, nisargshah2000 commented on parser/fg.lark
> +indendent_variable : ID
I will correct it in next commit.

2020-10-19 19:16 UTC, vedantsingh1404 commented on parser/fg.lark
> +ID : (LCASE_LETTER)+
@rajp152k should we add support for upper case variable names also? Won't make much difference though.

2020-10-19 19:17 UTC, vedantsingh1404 commented on parser/fg.lark
> +range_stmt : variable "<-" (points | range)
I agree, but I guess since this variable here is the independent one, why not reduce the clutter.

2020-10-19 19:18 UTC, vedantsingh1404 commented
Seems fine, merging this for now. The upper case changes can be made later as well.

2020-10-19 19:18 UTC, vedantsingh1404 approved these changes

2020-10-19 19:18 UTC, nisargshah2000 commented on parser/fg.lark
> +range_stmt : variable "<-" (points | range)
Changes done.

2020-10-19 19:19 UTC, merged

2020-10-20 04:11 UTC, rajp152k commented on parser/fg.lark
> +ID : (LCASE_LETTER)+
yeah, a matter of taste... 
maybe just enforce the first letter to be small and let the rest be alphanumeric + underscore for identifiers.
not of high priority right now.

2020-10-20 04:14 UTC, rajp152k reviewed
reviewed; 
basics all okay.
probably a few additions and changes in the future for 3d plots(eg:- what's dependent and independent will depend on the equations themselves)